(closes #6,#7) Split the main Bashelicious file in separate files + added plugins folder for custom user files

diff --git a/Bashelicious b/Bashelicious
--- a/Bashelicious
+++ b/Bashelicious
@@ -1,51 +1,23 @@
 #!/usr/bin/env bash
-# Initialize Bashelicious
 
-# Bashelicious exports
+################
+# Bashelicious #
+################
 export BASHELICIOUS_DIR=$HOME/.bashelicious
 export CDPATH=$CDPATH:.:~
 
-# Bashelicious aliases
-alias ls="ls -FG"
-alias ll="ls -lh"
-alias la="ls -Hlha"
-alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
-alias ..="cd .."
-alias ...="cd ../.."
-alias -- -="cd -"
-alias nano="nano -f"
-alias sshtunnel="sh $BASHELICIOUS_DIR/extra/sshtunnel.sh"
-
-# Bashelicious methods
-function compress() { tar -jcvf "$@" ;}
-function decompress() { tar -jxvf "$@" ;}
-function findproc() { ps aux | grep -i $1 | grep -v grep ;}
-
-function parse_git_branch_and_add_brackets {
-  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\ \[\1\]/'
+function bashelicious_import() {
+	[[ -f "${BASHELICIOUS_DIR}/$1" ]] && . ${BASHELICIOUS_DIR}/$1 || echo ":: Bashelicious failed to import file $1" >&2
 }
 
-# Color man pages:
-export LESS_TERMCAP_mb=$'\E[01;31m'      # begin blinking
-export LESS_TERMCAP_md=$'\E[01;31m'      # begin bold
-export LESS_TERMCAP_me=$'\E[0m'          # end mode
-export LESS_TERMCAP_se=$'\E[0m'          # end standout-mode
-export LESS_TERMCAP_so=$'\E[01;44;33m'   # begin standout-mode - info box
-export LESS_TERMCAP_ue=$'\E[0m'          # end underline
-export LESS_TERMCAP_us=$'\E[01;32m'      # begin underline
+# Load base files
+bashelicious_import lib/vars.sh
+bashelicious_import lib/alias.sh
+bashelicious_import lib/misc.sh
+bashelicious_import lib/functions.sh
 
-# bash completion settings
-bind "set completion-ignore-case on" # This ignores case in bash completion
-bind "set bell-style none" # Turn off bell
-bind "set show-all-if-ambiguous On" # Single tab completion
-bind Space:magic-space #auto expand ! variants upon space
-
-# shopts
-shopt -s cdspell # correct small spelling errors automagically
-shopt -s histappend # write to a shared history file for all shells
-
-# Completions
-[[ -e $BASHELICIOUS_DIR/extra/completions.sh ]] && . $BASHELICIOUS_DIR/extra/completions.sh
-
-# Prompt layout
-PS1="\[\e[0;32m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\]\[\e[1;32m\]\$(parse_git_branch_and_add_brackets) \[\e[1;32m\]\$\[\e[m\] "
+# Load plugins
+for PLUGIN in $(ls $BASHELICIOUS_DIR/plugins/*.plugin.sh)
+do
+	bashelicious_import plugins/$(basename $PLUGIN)
+done
